using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LibTmux.Generators;

/// <summary>Emits the closed catalog of queryable tmux format fields.</summary>
/// <remarks>
/// The catalog is generated rather than hand-written so the query vocabulary
/// stays closed: a field absent here cannot be translated, which is what makes
/// translate-or-throw enforceable instead of advisory.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class FieldCatalogGenerator : IIncrementalGenerator
{
    private static readonly (string WireName, string Target, bool Relation)[] Fields =
    {
        ("client_control", "Client", false),
        ("client_id", "Client", false),
        ("client_name", "Client", false),
        ("pane_command", "Pane", false),
        ("pane_id", "Pane", false),
        ("session_attached", "Session", false),
        ("session_id", "Session", false),
        ("session_name", "Session", false),
        ("session_windows", "Session", true),
        ("window_id", "Window", false),
        ("window_name", "Window", false),
        ("window_panes", "Window", true),
    };

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(static registration =>
            registration.AddSource(
                "QueryFieldCatalog.g.cs",
                SourceText.From(Render(), Encoding.UTF8)));

    private static string Render()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace LibTmux.Query;");
        source.AppendLine();
        source.AppendLine("internal static partial class QueryFieldCatalog");
        source.AppendLine("{");
        source.AppendLine(
            "    internal static bool IsRelation(string wireName) => wireName switch");
        source.AppendLine("    {");
        foreach ((string wireName, _, bool relation) in Fields)
        {
            if (relation)
            {
                source.AppendLine($"        \"{wireName}\" => true,");
            }
        }

        source.AppendLine("        _ => false,");
        source.AppendLine("    };");
        source.AppendLine();
        source.AppendLine(
            "    internal static bool TryGetTarget(string wireName, out QueryTarget target)");
        source.AppendLine("    {");
        source.AppendLine("        switch (wireName)");
        source.AppendLine("        {");
        foreach ((string wireName, string target, _) in Fields)
        {
            source.AppendLine($"            case \"{wireName}\":");
            source.AppendLine($"                target = QueryTarget.{target};");
            source.AppendLine("                return true;");
        }

        source.AppendLine("            default:");
        source.AppendLine("                target = default;");
        source.AppendLine("                return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    internal static IReadOnlyList<string> WireNames { get; } =");
        source.AppendLine("    [");
        foreach ((string wireName, _, _) in Fields)
        {
            source.AppendLine($"        \"{wireName}\",");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");
        return source.ToString();
    }
}
